import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiase`}
    >
      <body className="min-h-full min-w-full flex flex-col bg-white">
        <header className="h-16 flex py-4 px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-64 items-center justify-between bg-white text-black text-xl font-semibold ">
          {/* left  */}
          <div className="text-blue-700">Tailor Your Resume</div>
          {/* right */}
          <div className="text-blue-700">random Icons</div>
        </header>
        {children}
      </body>
    </html>
  );
}
